package com.blaizmiko.popcornapp.data.db.models.movies;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

@Entity
public class GenreDBModel {
    @Relation()
    DetailedMovieDBModel detailedMovieDBModel;
    @Id(assignable = true)
    long id;
    long detailedMovieDBModelId;
    String name;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(841027643)
    transient ToOne<DetailedMovieDBModel> detailedMovieDBModelToOne = new ToOne<>(
            this, GenreDBModel_.detailedMovieDBModel);
    @Generated(1087652684)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GenreDBModel(long id, long detailedMovieDBModelId, String name) {
        this.id = id;
        this.detailedMovieDBModelId = detailedMovieDBModelId;
        this.name = name;
    }
    @Generated(577336918)
    public GenreDBModel() {
    }
    /** To-one relationship, resolved on first access. */
    @Generated(1730563088)
    public DetailedMovieDBModel getDetailedMovieDBModel() {
        detailedMovieDBModel = detailedMovieDBModelToOne
                .getTarget(this.detailedMovieDBModelId);
        return detailedMovieDBModel;
    }
    /** Set the to-one relation including its ID property. */
    @Generated(924616133)
    public void setDetailedMovieDBModel(DetailedMovieDBModel detailedMovieDBModel) {
        detailedMovieDBModelToOne.setTarget(detailedMovieDBModel);
        this.detailedMovieDBModel = detailedMovieDBModel;
    }
}
