package com.blaizmiko.popcornapp.data.db.models.movies;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

@Entity
public class GenreDBModel {
    @Relation()
    @Expose(serialize = false)
    DetailedMovieDBModel detailedMovieDBModel;
    @Expose
    @Id(assignable = true)
    private long id;
    @Expose
    private String name;
    @Expose(serialize = false)
    private long detailedMovieDBModelId;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(1266234886)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GenreDBModel(long id, String name, long detailedMovieDBModelId) {
        this.id = id;
        this.name = name;
        this.detailedMovieDBModelId = detailedMovieDBModelId;
    }
    @Generated(577336918)
    public GenreDBModel() {
    }
    @Internal
    @Generated(841027643)
    transient ToOne<DetailedMovieDBModel> detailedMovieDBModelToOne = new ToOne<>(
            this, GenreDBModel_.detailedMovieDBModel);

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public long getDetailedMovieDBModelId() {
        return detailedMovieDBModelId;
    }
    public void setDetailedMovieDBModelId(long detailedMovieDBModelId) {
        this.detailedMovieDBModelId = detailedMovieDBModelId;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    /** To-one relationship, resolved on first access. */
    @Generated(1730563088)
    public DetailedMovieDBModel getDetailedMovieDBModel() {
        detailedMovieDBModel = detailedMovieDBModelToOne
                .getTarget(this.detailedMovieDBModelId);
        return detailedMovieDBModel;
    }
    /** Set the to-one relation including its ID property. */
    @Generated(924616133)
    public void setDetailedMovieDBModel(DetailedMovieDBModel detailedMovieDBModel) {
        detailedMovieDBModelToOne.setTarget(detailedMovieDBModel);
        this.detailedMovieDBModel = detailedMovieDBModel;
    }

}
