package com.blaizmiko.popcornapp.data.db.models.movies;

import com.google.gson.annotations.Expose;

import java.util.List;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;


@Entity
public class MoviesResponseDBModel {
    @Expose(serialize = false, deserialize = false)
    @Backlink
    List<DetailedMovieDBModel> detailedMovies = new ToMany<>(this, MoviesResponseDBModel_.detailedMovies);
    @Expose
    @Id
    private long id;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Generated(958671901)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public MoviesResponseDBModel(long id) {
        this.id = id;
    }
    @Generated(1531783334)
    public MoviesResponseDBModel() {
    }

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }

    public List<DetailedMovieDBModel> getMovies() {
        return detailedMovies;
    }
    public void setMovies(List<DetailedMovieDBModel> detailedMovies) {
        this.detailedMovies = detailedMovies;
    }
}


